codecov:
  branch: master
comment:
  behavior: default
  require_changes: true
coverage:
  range: 60..95
  round: down
  precision: 2
  status:
    changes: false
    project:
      default:
        target: 80.0
        threshold: 0.1
      fully_covered1:
        target: 100.0
        paths:
          - OpenQA
          - backend
          - consoles/VMWare.pm
          - consoles/VNC.pm
          - consoles/localXvnc.pm
          - consoles/network_console.pm
          - consoles/serial_screen.pm
          - consoles/sshSerial.pm
          - consoles/virtio_terminal.pm
          - bmwqemu.pm
          - log.pm
          - mmapi.pm
          - osutils.pm
          - signalblocker.pm
          - xt
      fully_covered2:
        target: 100.0
        paths:
          - t
    patch:
      default:
        branches: null
fixes:
  - "/opt/::"
