
in addition to this repo you also need to clone test cases and needles:

$ mkdir distri
$ cd distri
$ git clone git@github.com:os-autoinst/os-autoinst-distri-opensuse.git opensuse
$ cd opensuse
$ git clone git@github.com:os-autoinst/os-autoinst-needles-opensuse.git needles

== use of git repo with with openQA

to use os-autoinst with openQA it needs to be "installed". Placing a
symlink to /usr/lib/os-autoinst that points to the git checkout
should work. To make tests and needles writable don't touch distri/
and use tools/fetchneedles instead to set it up.


=== OUTDATED INSTALLATION ===
FIXME

as root:
echo "deb    http://ftp.de.debian.org/debian/  squeeze          main" > /etc/apt/sources.list.d/squeeze.list

cat >>/etc/apt/preferences <<EOF
Package: *
Pin: release o=Debian,a=testing
Pin-Priority: 40
EOF

aptitude update

aptitude install git-core kvm/testing ffmpeg2theora/testing gocr/testing multimon sox

echo kvm-intel >> /etc/modules


== openSUSE setup ==

    zypper ar -r http://r.opensu.se/devel:openQA/r
    zypper in os-autoinst

    usermod -G kvm -a $USERNAME || usermod -A kvm $USERNAME

== more Linux setup ==

modprobe kvm-intel || modprobe kvm-amd
chgrp kvm /dev/kvm ; chmod g+rw /dev/kvm # maybe redundant
# optionally use a new user; just to keep things separate
useradd -m USERNAME -G kvm
passwd USERNAME # and/or add ~USERNAME/.ssh/authorized_keys


== user setup ==

git clone http://www3.zq1.de/bernhard/git/autoinst.git/ autoinst
cp -a env.sh.sample env.sh
edit env.sh # see comments there ; adjust or drop HTTPPROXY and SUSEMIRROR lines


==VirtualBox Setup==
Install VirtualBox either from your distribution's DVD or 
From http://software.opensuse.org/package/virtualbox
After installation of VirtualBox do this
insmod vboxdrv
usermod -G vboxusers -a $USERNAME || usermod -A vboxusers $USERNAME
Log out and in and you are done

===Setting up OS-autoinst for VirtualBox===
add to env.sh:
export BACKEND=vbox
and create a Virtual Machine named "osautoinst" with at least 8GB of HDD

for usage see README
