#!/usr/bin/env perl
use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../lib"; # Ensure OpenQA namespace is in @INC
use OpenQA::Isotovideo::dewebsockify;

my %args;
GetOptions(\%args, 'websocketurl=s', 'listenport=s', 'cookie=s', 'loglevel=s', 'insecure', 'help|h|?')
  or usage(1);
usage(0) if $args{help};

OpenQA::Isotovideo::dewebsockify::main(\%args);

sub usage {
    print <<"END_USAGE";
Usage: $0 --websocketurl <URL> [--listenport <PORT>] [--cookie <COOKIE>] [--loglevel <LEVEL>] [--insecure]
Options:
  --websocketurl   The WebSocket server URL (required).
  --listenport     Port to listen on (default: 5900).
  --cookie         Cookie to include in WebSocket requests.
  --loglevel       Log level (default: 'info').
  --insecure       Allow insecure WebSocket connections.
  --help, -h, -?   Show this help message.
END_USAGE
    exit $_[0];
}

