#!/usr/bin/perl
# Copyright SUSE LLC
# SPDX-License-Identifier: GPL-2.0-or-later

=head1 SYNOPSIS

os-autoinst-openvswitch [OPTIONS]

=head1 OPTIONS

=over 4

=item B<-h, -?, --help>

Show this help.

=cut

################################################################################
package main;
use Mojo::Base -strict, -signatures;

use Net::DBus;
use Net::DBus::Reactor;
use FindBin '$Bin';
use lib "$FindBin::Bin/lib";

sub parse_args () {
    my %options;
    GetOptions(\%options, 'help|h|?') or usage(1);
    usage(0) if $options{help};
    return \%options;
}

sub main ($args) {
    my $bus = Net::DBus->system;
    my $service = $bus->export_service("org.opensuse.os_autoinst.switch");
    my $object = OVS->new($service);

    Net::DBus::Reactor->main->run;
}

main(parse_args()) unless caller();
