#!/usr/bin/perl
use Test::Most;
use Mojo::Base -signatures;
use FindBin '$Bin';
use lib "$Bin/../external/os-autoinst-common/lib";
use OpenQA::Test::TimeLimit '5';
use Test::Warnings ':report_warnings';

use File::Basename;
use File::Path qw(make_path remove_tree);
use Cwd;
use OpenQA::Benchmark::Stopwatch;
use cv;

cv::init();
require tinycv;

my $data_dir = dirname(__FILE__) . '/data/';
my $img1 = tinycv::read($data_dir . 'xorg_vt-Xorg-20140729.png');
my $ppm = $img1->ppm_data();
my $ppmv = $ppm;
$ppmv =~ s,# Generated by OpenCV \S+\s,,;
# make sure we don't explode in case of failure
$ppmv = substr $ppmv, 0, 80;
like $ppmv, qr/^P6\s1024 768\s255/, 'is a ppm';
my $img2 = tinycv::from_ppm($ppm);

is 1_000_000, $img1->similarity($img2);

throws_ok { $img1->write_with_thumbnail('/tmp/does-not-exist/test.png') } qr/Unable to write.*test\.png/, 'dies when image cannot be written';

throws_ok { $img1->write_with_thumbnail('/tmp/does-not-exist/test') } qr/Could not write.*test/, 'dies when OpenCV error occurs';

subtest 'scale' => sub {
    my $exact = $img1->scale(1024, 768);
    is $exact->xres, 1024, 'exact-size scale keeps width';
    is $exact->yres, 768, 'exact-size scale keeps height';
    is $exact->similarity($img1), 1_000_000, 'exact-size scale is pixel-identical';

    my $padded = $img1->scale(1200, 900);
    is $padded->xres, 1200, 'padded scale has requested width';
    is $padded->yres, 900, 'padded scale has requested height';
    is_deeply [$padded->get_pixel(0, 0)], [$img1->get_pixel(0, 0)], 'padded scale preserves original pixel';
    is_deeply [$padded->get_pixel(1100, 850)], [120, 120, 120], 'padded scale pads with gray';

    my $down = $img1->scale(512, 384);
    is $down->xres, 512, 'scaled-down width';
    is $down->yres, 384, 'scaled-down height';
};

done_testing();
