#!/usr/bin/perl -w
use strict;
use bmwqemu;
use autotest;
$scriptdir=`dirname $scriptdir`;chomp($scriptdir); # one level up

print "====\n"; # marker

my @stages=(qw"splashscreen welcome timezone disk usersettings installationoverview performinstallation automaticconfiguration booted");

my %stageseen=();
my %md5seen=();
while(<>) {
	if(/stage=([0-9a-zA-Z_.-]*) ([0-9a-f]+)/) {
		$stageseen{$1}=1;
		$md5seen{$2}=1;
	}
	if(/md5=([0-9a-f]+)/) {$md5seen{$1}=1}
}

my %results;
foreach my $s (@stages) {
	my $found=0;
	foreach(keys(%stageseen)) {if(m/$s/){$found=1;last;}}
	my $result=$results{$s}=($found?"OK":"fail");
	print "$s: $result\n";
}

sub checkfunc
{
	my($test)=@_;
	my $class=ref $test;
	my $result=$test->check(\%md5seen)||"unknown";
	print "$class: $result\n";
	$results{$class}=$result;
}

autotest::runtest("suseinst.d/010_initenv.pm",sub{my $test=shift;$test->run;});

autotest::runtestdir("$scriptdir/inst.d", \&checkfunc);
autotest::runtestdir("$scriptdir/consoletest.d", \&checkfunc);
autotest::runtestdir("$scriptdir/x11test.d", \&checkfunc);

my $overall=($results{xterm} eq "OK" or $results{firefox} eq "OK");
for my $test (qw(automaticconfiguration booted zypper_in zypper_up yast2_lan)) {
	$overall=0 if $results{$test} ne "OK";
}

print "overall: ".($overall?"OK":"fail")."\n";

