#!/bin/sh -e
# fall back to find if there is no git, e.g. in package builds
# shellcheck disable=SC2046
RADON="${1:-radon}"
set -- $(git ls-files "*.py" 2> /dev/null || find . -name '*.py')
"$RADON" mi "$@" -n B | (! grep ".")
