#!/bin/sh -e
# fall back to find if there is no git, e.g. in package builds
# shellcheck disable=SC2046
"${1:-yamllint}" --strict $(git ls-files "*.yml" "*.yaml" 2>/dev/null || find . -name '*.y*ml')
