#!/bin/sh -e
# fall back to find if there is no git, e.g. in package builds
# shellcheck disable=SC2046
VULTURE="${1:-vulture}"
set -- $(git ls-files "*.py" 2> /dev/null || find . -name '*.py')
"$VULTURE" "$@" --min-confidence 80 --exclude t/fake/tests/faulty.py
