#!/bin/bash -e
CI_ENV=$(bash <(curl -s https://codecov.io/env))
# shellcheck disable=SC2086

IMAGE=registry.opensuse.org/devel/openqa/containers/os-autoinst_dev
docker pull $IMAGE
docker images | grep opensuse

docker run --env "QEMU_QMP_CONNECT_ATTEMPTS=10" --env "EXPECTED_ISOTOVIDEO_RUNTIME=20" \
  $CI_ENV --rm --entrypoint '' -v "$PWD":/opt $IMAGE sh -ec '
cd /opt
./tools/install-new-deps.sh
cmake -G Ninja -DCMAKE_BUILD_TYPE=Release .
export WITH_COVER_OPTIONS=1
ninja -v check
ninja -v coverage-codecov'
