#!/bin/bash -e

# process arguments
if [[ $1 == --coverage ]]; then
    WITH_COVER_OPTIONS=1
    shift
fi
if [[ $# -lt 3 ]]; then
    echo "usage: $0 [--coverage] prove-tool-path make-tool-path build-directory [test-file...]"
    exit
fi
prove_path=$1 make_path=$2 build_dir=$3
shift 3
test_files=("$@")

# set Perl module include path and coverage options
export PERL5LIB="$PWD:$PWD/ppmclibs:$PWD/ppmclibs/blib/arch/auto/tinycv:$PERL5LIB"
if [[ $WITH_COVER_OPTIONS ]]; then
    path_regex="^|$PWD/|\\.\\./"
    export PERL5OPT="-MDevel::Cover=-db,$build_dir/cover_db,-select,($path_regex)(OpenQA|backend|consoles|ppmclibs)/|($path_regex)isotovideo|($path_regex)[^/]+\.pm,-ignore,\.t|data/tests/|fake/tests/|$prove_path,-coverage,statement"
fi

# set variables for tests which need to invoke the make tool
export OS_AUTOINST_BUILD_DIRECTORY=$build_dir
export OS_AUTOINST_MAKE_TOOL=$make_path

# allow specifying the list of tests via TESTS in consistency with openQA; otherwise run all tests
[[ ${#test_files[@]} -lt 1 ]] && test_files=($TESTS)
[[ ${#test_files[@]} -lt 1 ]] && test_files=(-r)

# invoke tests within the t directory
cd t && "$prove_path" $PROVE_ARGS "${test_files[@]}"
