#!/bin/bash

if test -z "$NAME" ; then
	echo "\$NAME must be set!" >&2
	exit 1
fi
scriptdir=$(dirname $(dirname $0))
logfile=autoinst-log.txt

echo testing $NAME
# cleanup
test -e qemu.pid && kill `cat qemu.pid` 2>/dev/null && rm -f qemu.pid
rm -f backend.run

# start
TZ=UTC date "+%s%n%Y-%m-%d %H:%M:%S" > ${logfile}

osautoinstpid=
exithandler()
{
	echo "isotovideo exit handler $osautoinstpid" >&2
	if [ -n "$osautoinstpid" ]; then
		kill $osautoinstpid
	fi
}
if [ -t 0 ]; then
	2> stderr.txt
	exec 7> >(tee stderr.txt)
else
	exec 7>stderr.txt
fi
trap exithandler EXIT
perl $scriptdir/start.pl 2>&7 &
osautoinstpid=$!
wait $!
echo "start.pl exited with status $?"
unset osautoinstpid

test -e qemu.pid && kill `cat qemu.pid` 2>/dev/null && rm -f qemu.pid
rm -f backend.run
echo "QEMU finished, running final checks" >> ${logfile}

echo "+++ STDERR +++" >> ${logfile}
cat stderr.txt >> ${logfile}

