#!/usr/bin/perl -w
use strict;

my $in=shift;
my $out=shift;

if(!$in || !$out) {die "usage: $0 IN OUT"}

my $tmpdir="ppmtompg.tmp";
system("rm -rf $tmpdir");
mkdir $tmpdir;
my $n=0;
for my $f (<$in/*.ppm>) {
	link($f, sprintf("%s/%08d.ppm", $tmpdir, $n++));
}

my @bw=();
#@bw=("-V", "700");
system("ffmpeg2theora", @bw, "$tmpdir/%08d.ppm", "-F", 12, "-o", "$out.ogv");

#system("rm -rf $tmpdir");
