#!/usr/bin/perl -w
use strict;

my $in=shift;
my $out=shift;

if(!$in || !$out) {die "usage: $0 IN OUT"}

my $tmpdir="ppmtompg.tmp";
system("rm -rf $tmpdir");
mkdir $tmpdir;
my $biggest=0;
my $biggestf;
for my $f (<$in/*.ppm>) {
	my $s=-s $f;
	if($s>$biggest){$biggest=$s; $biggestf=$f}
}
my $n=0;
for my $f (<$in/*.ppm>) {
	if($n==0) { $f=$biggestf; } # work around ffmpeg2theora using first frame size for whole video
	link($f, sprintf("%s/%08d.ppm", $tmpdir, $n++));
}

my @bw=();
#@bw=("--videobitrate", "700", "--no-upscaling");
system("ffmpeg2theora", @bw, "--inputfps", 12, "$tmpdir/%08d.ppm", "--max_size","800x600", "--framerate", 12, "-o", "$out.ogv");


system("rm -rf $tmpdir");
