#!/bin/bash

export HWSLOT=$1
while read -n 1 -p "> " i ; do
	test "$i" == "" && i="backspace"
	test "$i" == "#" && i="ret"
	test "$i" == "" && i="spc"
	if [[ "$i" == "^" ]] ; then
		echo
		read -p "com> " i
	fi
	perl -e 'use backend::kvm2usb; my $k=backend::kvm2usb->new(); $k->sendkey("'$i'");'
done
