#!/bin/bash

set -euo pipefail

cre="${cre:-"podman"}"
for i in container/*/Dockerfile*; do
    echo "$0 => Testing container $i"
    tag=${i,,}
    $cre build -t "$tag" -f "$i" "$(dirname "$i")"/
    $cre run --rm "$tag" --help
done
