---
name: ci
# yamllint disable-line rule:truthy
on: [push, pull_request]
env:
  # Set to 1 to temporarily ignore warnings
  PERL_TEST_WARNINGS_ONLY_REPORT_WARNINGS: 0
jobs:
  test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7
      - name: Static checks, unit tests and integration tests
        run: tools/container_run_ci
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f  # v7
        with:
          # should not be necessary for public repos, but might help avoid sporadic upload token errors
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./build/cover_db/codecov.json
          fail_ci_if_error: true
          verbose: true
      - run: |
          tar cvf coverage.tar build/cover_db
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7
        with:
          name: coverage
          path: coverage.tar
          retention-days: 15
      - run: ./tools/check-line-coverage build/cover_db/codecov.json
  static-check-containers:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7
      - name: Test our container definitions
        run: tools/static_check_containers
