---
name: openQA Fullstack
# yamllint disable-line rule:truthy
on:
#  push:
#  pull_request:
  workflow_dispatch:
    inputs:
      stability_test:
        description: 'Set to 1 to fail if any of the RETRY fails'
        default: 0
env:
  # Set to 1 to temporarily ignore warnings
  PERL_TEST_WARNINGS_ONLY_REPORT_WARNINGS: 0
  # Default user in the used container image from
  # https://github.com/os-autoinst/openQA/blob/master/container/devel%3AopenQA%3Aci/base/Dockerfile
  NORMAL_USER: squamata

jobs:
  fullstack:
    runs-on: ubuntu-latest
    container:
      image: registry.opensuse.org/devel/openqa/ci/containers/base:latest
      # See https://docs.github.com/en/actions/creating-actions/dockerfile-support-for-github-actions#user
      options: --user root
    steps:
      - uses: actions/checkout@v4
      - name: Make project folder user-writable
        run: chown -R $NORMAL_USER ../../os-autoinst
      - name: Clone openQA
        run: >-
          sudo -u $NORMAL_USER
          git clone --depth 1 https://github.com/os-autoinst/openQA.git ../openQA
      - name: Install dependencies
        run: (cd ../openQA; bash -x tools/ci/build_cache.sh; sudo npm install)
      - name: Build os-autoinst
        run: sudo -u $NORMAL_USER make symlinks
      - name: Run unit tests
        run: sudo -u $NORMAL_USER make -C ../openQA test-fullstack
        env:
          STABILITY_TEST: ${{ github.event.inputs.stability_test }}
