---
name: openQA Fullstack
# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      stability_test:
        description: 'Set to 1 to fail if any of the RETRY fails'
        default: 0
env:
  # Set to 1 to temporarily ignore warnings
  PERL_TEST_WARNINGS_ONLY_REPORT_WARNINGS: 0

jobs:
  fullstack:
    runs-on: ubuntu-latest
    container:
      image: registry.opensuse.org/devel/openqa/ci/containers/base:latest
    steps:
      - uses: actions/checkout@v1
      - name: Make project folder user-writable
        run: sudo chown -R $USER ../../os-autoinst
      - name: Clone openQA
        run: git clone --depth 1 https://github.com/os-autoinst/openQA.git ../openQA
      - name: Install dependencies
        run: (cd ../openQA; bash -x tools/ci/build_cache.sh)
      - name: Build os-autoinst
        run: make symlinks
      - name: Run unit tests
        run: make -C ../openQA test-fullstack
        env:
          STABILITY_TEST: ${{ github.event.inputs.stability_test }}
